### ISSUE TITLE
스크롤 내린 후 뒤로가기

### ISSUE THREAD

**Issue by Hoseong-Ryu** [joog-lim/bamboo-android#14]
스크롤을 내린 뒤에 백프레스를 누르면 백프레스를 눌렀을때 까지의 아이템만 나옴

**Comment by sunrabbit123** [comment]
버그 제보 감사합니다!

빠른 시일내로 개발자들에게 전달하여 업데이트 하도록 조치하도록 하겠습니다. 
이번 버그 패치 업데이트를 하면서, 버그가 생겨난 것 같습니다.

버그 발생시의 자세한 상황을 설명해주시면, 더 빠른 버그 픽스를 불러올 수 있습니다!

**Comment by sunrabbit123** [comment]
11월 4일자 v2.0.2 버전으로 업데이트를 진행하며 해당 버그를 고쳤습니다.
버그 제보 다시한번 감사드립니다.
